Fixed a race condition when attaching to an existing socket
novnc/noVNC pull request #1537
Opened 2021-03-23 13:06 UTC by TimSBSquare

This is an error that presents itself with RTCDataChannel's, I suspect this could not
happen with a pre-existing WebSocket.

If the remote connection creates a data channel then the local (VNC) side gets a channel
created callback. It may also be the case that in that very same tick the socket is also
opened and buffered data received. This meant that (in my tests) about 1/3 of the time
noVNC would fail to respond to the initial message from the server because it was received
and subsequently not handled during that initial tick.

I'm not sure if this is the correct way to fix this. It is the only way I could see short of changing the noVNC flow to construct, attach listeners, then call a new open() method with the url or channel.

2021-03-30 13:01 UTC, samhed requested changes
Your reasoning makes sense to me, the change looks fine. I haven't tested connections using a WebRTC, but a regular socket still works fine. What VNC server has support for WebRTC?

Just one minor nitpick in the code.

2021-03-30 13:23 UTC, timstableford commented on core/rfb.js
> +            setTimeout(this._updateConnectionState.bind(this, "connecting"));
I'll use all single quotes, it was a difficult choice because the file doesn't have consistent quoting sadly

2021-03-30 13:35 UTC, TimSBSquare commented on core/rfb.js
> +            setTimeout(this._updateConnectionState.bind(this, "connecting"));
Switched to single quotes

2021-03-30 13:40 UTC, TimSBSquare commented
@samhed As far as I'm aware there's no publicly VNC servers or connectors that make use of RTCDataChannel's. It's something the company I work for is building into some of their software. I suspect for most users of this library it wouldn't be particularly useful because RTCDataChannel's require a signalling channel to open the connection, such as a pre-existing MQTT connection.
The bug could present itself with WebSocket's though under certain circumstances. If the user of the library listened for the WebSocket's open event and only then created RFB with the WebSocket object.

2021-03-30 13:46 UTC, samhed commented
I see. How does the bug appear to the end user when data gets lost this way?

2021-03-30 13:56 UTC, TimSBSquare commented
In my testing a grey screen where the VNC window is. It's the same as if the VNC client doesn't receive the initial handshake from the server.

2021-03-30 13:59 UTC, merged

2021-04-16 11:27 UTC, CendioOssman commented
Sorry, but I'm afraid this is a hard NAK for me. Removing that timeout creates other races so this is not the proper way to go about this.

I'm going to revert this commit and we'll need to have a deeper look at how to handle your case.