Add MSLogonII security type
novnc/noVNC pull request #1731
Opened 2022-12-18 05:18 UTC by pdlan

This PR adds UltraVNC's MSLogonII security type, which resolves #1197.

2022-12-21 14:51 UTC, CendioOssman requested changes
Nice, thank you! Looks good, with just two small comments.

2022-12-21 14:51 UTC, CendioOssman commented on core/rfb.js
> +const securityTypeUltraVNCMSLogonII = 113;
Perhaps just "MSLogonII" is sufficient? Keeps the length down on identifiers.

2022-12-21 14:51 UTC, CendioOssman commented on tests/test.rfb.js
> -import DES from "../core/des.js";
Please merge this in to the previous commit.

2022-12-22 13:18 UTC, CendioOssman approved these changes
Nice. Thank you for your contribution!

2022-12-23 13:43 UTC, merged

2022-12-23 19:26 UTC, Neustradamus commented
@pdlan: Thanks a lot!