Fix unescaped optargs in websockify command
novnc/noVNC pull request #1741
Opened 2022-12-31 18:16 UTC by tutacat

When passing a path with spaces to websockify, it is incorrectly read as multiple arguments, because the args weren't enclosed in quotes.

2023-01-03 14:44 UTC, CendioOssman requested changes
Thank you for your fix!

I'm afraid it isn't entirely correct, though. Please have a look at the comment.

2023-01-03 14:44 UTC, CendioOssman commented on utils/novnc_proxy
> +    --syslog) SYSLOG_ARG='--syslog "${OPTARG}"'; shift ;;
I'm afraid `'` disables variable expansion, so this won't work.

2023-07-24 12:55 UTC, samhed commented
@tutacat do you think you will get a chance to fix this?

2023-08-22 14:10 UTC, CendioOssman commented
This looks better, but unfortunately, it still doesn't work. It is still splitting the words for the record, syslog and auth arguments.

2024-08-08 11:42 UTC, CendioOssman commented
No response. Closing.

2024-08-08 11:42 UTC, closed without merging

2024-08-11 11:19 UTC, tutacat commented
Yes. I am a "volounteer". Not 100% of my time is github. Not all minds work the same, either.

2024-08-12 12:20 UTC, CendioOssman commented
I understand, and we do try to give some time before we consider something abanonded.

I can gladly reopen it if it's not abandoned and you'd like to resume the work?

2024-08-28 16:35 UTC, tutacat commented
hiya sorry about this pull, it was easier to make [a new one](1891)